"""empty message

Revision ID: c336b1cbd356
Revises: a5119c8b9a78
Create Date: 2019-10-25 10:40:09.139431

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = 'c336b1cbd356'
down_revision = 'a5119c8b9a78'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('i_order',
    sa.Column('create_time', sa.DateTime(), nullable=True),
    sa.Column('update_time', sa.DateTime(), nullable=True),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.Column('house_id', sa.Integer(), nullable=True),
    sa.Column('begin_date', sa.DateTime(), nullable=False),
    sa.Column('end_data', sa.DateTime(), nullable=False),
    sa.Column('days', sa.Integer(), nullable=False),
    sa.Column('house_price', sa.Integer(), nullable=False),
    sa.Column('amount', sa.Integer(), nullable=False),
    sa.Column('status', sa.Enum('WAIT_ACCEPT', 'WAIT_PAYMENT', 'PAID', 'WAIT_COMMRNT', 'COMPLETE', 'CANCELED', 'REJECTED'), nullable=True),
    sa.Column('comment', sa.Text(), nullable=True),
    sa.Column('trade_no', sa.String(length=80), nullable=True),
    sa.ForeignKeyConstraint(['house_id'], ['i_house.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['i_user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_i_order_status'), 'i_order', ['status'], unique=False)
    op.drop_index('ix_order_status', table_name='order')
    op.drop_table('order')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('order',
    sa.Column('create_time', mysql.DATETIME(), nullable=True),
    sa.Column('update_time', mysql.DATETIME(), nullable=True),
    sa.Column('id', mysql.INTEGER(display_width=11), autoincrement=True, nullable=False),
    sa.Column('user_id', mysql.INTEGER(display_width=11), autoincrement=False, nullable=True),
    sa.Column('house_id', mysql.INTEGER(display_width=11), autoincrement=False, nullable=True),
    sa.Column('begin_date', mysql.DATETIME(), nullable=False),
    sa.Column('end_data', mysql.DATETIME(), nullable=False),
    sa.Column('days', mysql.INTEGER(display_width=11), autoincrement=False, nullable=False),
    sa.Column('house_price', mysql.INTEGER(display_width=11), autoincrement=False, nullable=False),
    sa.Column('amount', mysql.INTEGER(display_width=11), autoincrement=False, nullable=False),
    sa.Column('status', mysql.ENUM('WAIT_ACCEPT', 'WAIT_PAYMENT', 'PAID', 'WAIT_COMMRNT', 'COMPLETE', 'CANCELED', 'REJECTED'), nullable=True),
    sa.Column('comment', mysql.TEXT(), nullable=True),
    sa.Column('trade_no', mysql.VARCHAR(length=80), nullable=True),
    sa.ForeignKeyConstraint(['house_id'], ['i_house.id'], name='order_ibfk_1'),
    sa.ForeignKeyConstraint(['user_id'], ['i_user.id'], name='order_ibfk_2'),
    sa.PrimaryKeyConstraint('id'),
    mysql_default_charset='utf8',
    mysql_engine='InnoDB'
    )
    op.create_index('ix_order_status', 'order', ['status'], unique=False)
    op.drop_index(op.f('ix_i_order_status'), table_name='i_order')
    op.drop_table('i_order')
    # ### end Alembic commands ###
